### ISSUE TITLE
Agregar bundle analyzer en CI

### ISSUE THREAD

**Issue by durancristhian** [meetupjs-ar/meetupjs-ar.github.io#108]
Estaría piola que corramos esto en el CI (yo pensé que se estaba corriendo) y que los archivos esos se publiquen para que podamos ver que es lo que hay en prod

**Comment by durancristhian** [comment]
Bueno, ya agregué en el README como hacer para obtener el reporte (`ANALYZE_BUNDLE npm run build`).

Teoría: Sin querer y por como estamos haciendo un [require mafioso](https://github.com/meetupjs-ar/meetupjs-ar.github.io/blob/dev/components/Blog/PostPage.jsx#L15), se nos da la situación de que en los bundles del blog (listado y cada artículo) ESTAMOS INCLUYENDO TODO EL BLOG ENTERO y en base a una prop del componente que viene desde la page, se muestra una cosa o la otra. Podemos confirmar esto?

Supongo que es porque no puede webpack (o next) interpretar en build time a cual de todos los mdx nos referimos por la prop y entonces mete todo por las dudas. 

_Por si se necesita contexto, desde el componente página en pages/articulos se le pasa la prop para que el require mafioso funcione_.

<img width="1667" alt="Screen Shot 2019-11-21 at 23 20 12" src="https://user-images.githubusercontent.com/4248944/69392707-aaa86d00-0cb5-11ea-8af2-868e5c115133.png">

@sergiodxa vos tenés idea como solucionar esto?

**Comment by durancristhian** [comment]
Por otro lado, sigo averiguando como hacer para que el archivo ese esté escondido en la subida a github pages y podamos verlo online con lo que hay en prod.

**Comment by sergiodxa** [comment]
Tengo que ver cómo lo hacen pero no debería estar pasando, los artículos son MDX no? Deberías poder exportar un layout y que cada .mdx sea su propia página, así hacen en ZEIT y hacia en mi blog personal cuando usaba Next.

Creo recordar que ZEIT tiene un repo que sirve de template para armar un blog con Next y MDX, capaz puedas revisar ahí la implementación?
