### ISSUE TITLE
Armar listado/repo/bot de slack de ofertas de laburo

### ISSUE THREAD

**Issue by nikoferro** [meetupjs-ar/meetupjs-ar.github.io#16]
La idea la tiro @durancristhian en #jobs, y para poner primera, hablandolo con el, quedamos en armar un issue aca para discutir las opciones:

Tiro un par de ideas que le pase a el:

**Opcion 1:**

Un microservicio con una pequeña api que reciba datos de un formulario en la web (me imagino guardando la data en una cuenta gratis de mongolabs)

**Opcion 2:**

Lo mismo que la 1, solo que en lugar de guardar a una DB, que se guarde en un spreadsheet de google (quiza mas facil de editar/mantener/hacer cambios)

**Opcion 3:**

Algo directo sin tener nada server side que sea cliente --> google spreadsheets (no conozco la api de google para esto, pero casi seguro que tiene que haber algo)

Para mostrar las ofertas en la web, me imagino que opciones 1/2 lo hacemos con un get a la api, y opcion 3 al spreadsheet en el caso de que google tenga una api para eso.

🤖Todas van con un bot de slack 🤖

**Comment by durancristhian** [comment]
Sea lo que sea que hagamos, lo que me coparía acá es *escribir la menor cantidad de código posible*. Por los siguientes motivos:

- una planilla de cálculo, un google form lo puede editar alguien que no necesariamente es programador

- menos código que mantener es mejor para todos :D

// =========================

Mi propuesta.

1. Armar un google form (*muy detallado*) de todos lo que podríamos preguntar, tipo de trabajo (remoto, no remoto), años de experiencia, link de contacto, etc. e incluso un campo en blanco para que se redacte. Esto lo tendríamos que pensar bien, pero bueno, es un google form...

Es muy importante que al completar el form, dejemos el mail de meetup.js para cualquier consulta. Por ejemplo, dar de baja una oferta.

2. Ese google form completa una spreadsheet y nos manda un mail. Inicialmente, diría que todo lo que se mande por el form, *quede oculto* hasta que alguien de meetup.js (para eso sirve el mail) lo revise y de el aprobado de la propuesta (está completa, no tiene lenguaje inapropiado, etc.). Si está aprobada, se cambia una columna en la planilla que usaríamos para decir: "este artículo está aprobado".

3. Armar una página en el sitio (`/trabajos`) que haga un fetch de la planilla (usando `gsheets` de npm), liste las ofertas y te deje ver el detalle.

En ambas páginas, pondría un link con mailto a nuestra cuenta para dar de baja una propuesta (si sos empleador) o notificar por alguna razón.

En base a las columnas del form (1) podemos pre armar filtros y tener eso disponible en el cliente para filtrar si tenemos muchas propuestas.

// =========================

Todo lo que tenga que ver con implementación, lo podemos discutir más adelante.

Que te parece @nikoferro ?

**Comment by nikoferro** [comment]
Esta muy buena, y coincide bastante con lo que tenia pensado como opcion mas simple. Tenes razon aparte que un spreadsheet seria mucho mas facil para alguien no tecnico para hacer cambios (de otra manera para hacer updates a una base de datos, tendriamos que hacer la implementacion mas compleja)

Con respecto al tema de los campos, estaria bueno consultar a los recruiters que postean en el canal de slack para ver cuales serian las "necesidades"
