### ISSUE TITLE
Agregar un jorgeucano flotando

### ISSUE THREAD

**Issue by hrajchert** [meetupjs-ar/meetupjs-ar.github.io#25]
Me parece muy importante para la comprensión de este sitio que haya una imagen de @jorgeucano flotando en el home.

Desde ya muchas gracias.

**Comment by hernimen** [comment]
Alguien pudo ver esto?

**Comment by durancristhian** [comment]
Hecho! Desde la versión 3.3.1 tenemos a jorge flotando en la home como los demás íconos

**Comment by hrajchert** [comment]
![brent](https://user-images.githubusercontent.com/2634059/46628182-1dd33c00-cb13-11e8-86fc-afb02f63f08a.gif)

**Comment by hernimen** [comment]
Buen laburo!! :D 👍
