### ISSUE TITLE
El link para agregar eventos está roto.

### ISSUE THREAD

**Issue by gusma** [meetupjs-ar/meetupjs-ar.github.io#30]
El link al form de google está roto.

----

<img width="883" alt="screen shot 2018-10-14 at 04 46 02" src="https://user-images.githubusercontent.com/140903/46913881-22ad4b00-cf6c-11e8-859f-896cbb3951a3.png">

**Comment by durancristhian** [comment]
No! Que habrá pasado? Gracias por reportarlo. Hoy mismo lo arreglo.

**Comment by durancristhian** [comment]
Solucionado! Resulta que next.js (el framework de React que estamos usando) no se por que modificaba el link que yo estoy poniendo en un componente <Link> y le estaba agregando la barra del final (/), si le sacas esa barra el link estaba bien. El fix consistió en usar un tag <a> común y corriente.

Corregido en https://github.com/meetupjs-ar/meetupjs-ar.github.io/commit/5df4574c4143584c4cfecc4433a3e6cfe09031bb
