### ISSUE TITLE
Actualizar link de Meetup a Eventbrite

### ISSUE THREAD

**Issue by sergiodxa** [meetupjs-ar/meetupjs-ar.github.io#85]
En la Home hay un link a Meetup.com

https://github.com/meetupjs-ar/meetupjs-ar.github.io/blob/dev/components/Home/HomePage.jsx#L115

Debería ir a EventBrite ahora

**Comment by durancristhian** [comment]
Buen dato colega pero creo que ese link va a quedar ahí hasta que definitivamente podamos dejar de usar meetup. La idea es que eventbrite no lo usemos como "el nuevo meetup" sino que solo publiquemos los eventos por ahí y por medio de otra plataforma (mailchimp) anunciar nosotros los eventos y tener en el sitio un banner para suscribirte. Todavía estamos trabajando en eso así que hasta que no lo tengamos creo que link quedará.

Tenemos que hablar por el issue de tu charla 👀 jaja
Cierro el issue
