### ISSUE TITLE
Que hacemos con el calendario ahora que está rota nuestra integración con meetup?

### ISSUE THREAD

**Issue by durancristhian** [meetupjs-ar/meetupjs-ar.github.io#89]
Sería mejor sacar el calendario?

**Comment by durancristhian** [comment]
@mateosilguero creo que nos conviene matar el calendario de meetups :(
Deberíamos también sacar el isnabot y eso

**Comment by mateosilguero** [comment]
Yo estuve intentando ver si se podia obtener esa data, pero es complicado y poco escalable.
Habra que evangelizar que otras comunidades se muevan a eventbrite
